services:
  orthanc-cache:
    build: .
    ports:
      - "8042:8042"
    volumes:
      - ./orthanc-cache:/orthanc-cache
      - ./.data/orthanc-cache:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: "orthanc-cache-plugin"

      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/orthanc-cache/server.py"
      ORTHANC__PYTHON_VERBOSE: "true"
  orthanc:
    image: osimis/orthanc
    ports:
      - "8043:8042"
    volumes:
      - ./.data/orthanc:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: "orthanc"