services:
  orthanc:
    build: .
    ports:
      - "8042:8042"
    volumes:
      - ./orthanc-cache:/orthanc-cache
    environment:
      ORTHANC__NAME: "orthanc-cache-plugin"

      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__PYTHON_SCRIPT: "/orthanc-cache/server.py"
      ORTHANC__PYTHON_VERBOSE: "true"