services:
  orthanc-cache:
    build: .
    ports:
      - "8042:8042"
    volumes:
      - ./orthanc_cache_plugin:/usr/share/orthanc/plugins/orthanc_cache_plugin
      - ./example.py:/tmp/example.py
      - ./.data/orthanc-cache:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: "Orthanc With Cache Plugin Enabled"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__STABLE_AGE: 3
      ORTHANC__PYTHON_SCRIPT: "/tmp/example.py"
      ORTHANC__PYTHON_VERBOSE: "true"
  orthanc:
    image: osimis/orthanc
    ports:
      - "8043:8042"
    volumes:
      - ./.data/orthanc:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: "Orthanc"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      ORTHANC__STABLE_AGE: 3