name: k6 tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate fixtures
        run: ./tests/fixtures.sh

      - name: Build orthanc-cache image
        run: docker compose build orthanc-cache

      - name: Start services
        run: docker compose up -d

      - name: Run ImportDicom.test.js
        run: |
            k6 run --out json=/tmp/import-dicom-1.json /github/workspace/tests/smoke/ImportDicom.test.js http://localhost:8042
            k6 run --out json=/tmp/import-dicom-2.json /github/workspace/tests/smoke/ImportDicom.test.js http://localhost:8043
            k6 convert /tmp/import-dicom-1.json
            k6 convert /tmp/import-dicom-2.json

      - name: Run IfModifiedSince.test.js
        run: |
          k6 run --out json=/tmp/if-modified-since.json /github/workspace/tests/smoke/IfModifiedSince.test.js http://localhost:8042
          k6 convert /tmp/if-modified-since.json

      - name: Run IfNoneMatch.test.js
        run: |
          k6 run --out json=/tmp/if-none-match.json /github/workspace/tests/smoke/IfNoneMatch.test.js http://localhost:8042
          k6 convert /tmp/if-none-match.json

      - name: Run ServerSideCaching.test.js
        run: |
          k6 run --out json=/tmp/server-side-caching-1.json /github/workspace/tests/load/ServerSideCaching.test.js http://localhost:8042
          k6 run --out json=/tmp/server-side-caching-2.json /github/workspace/tests/load/ServerSideCaching.test.js http://localhost:8043
          k6 compare /tmp/server-side-caching-1.json /tmp/server-side-caching-2.json

      - name: Run ClientSideCaching tests
        run: |
          k6 run --out json=/tmp/client-side-caching-1.json /github/workspace/tests/load/ClientSideCaching.test.js http://localhost:8042
          k6 run --out json=/tmp/client-side-caching-2.json /github/workspace/tests/load/ClientSideCaching.test.js http://localhost:8043
          k6 compare /tmp/client-side-caching-1.json /tmp/client-side-caching-2.json

      - name: Stop services
        run: docker-compose down
